esphome:
  name: xiaomi_air_purifier
  platform: esp32
  board: esp32dev
  build_path: .build
  platformio_options:
    platform: espressif32@1.11.0
    platform_packages: |-4
          framework-arduinoespressif32 @ https://github.com/pauln/arduino-esp32.git#solo-no-mac-crc/1.0.4

  includes:
    - miiot_uart.h
    - xiaomi_air_purifier.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_fallback_ssid
    password: !secret wifi_fallback_password

captive_portal:

web_server:
  port: 80

# Enable Home Assistant API
api:

ota:

# Enable logging
logger:
  level: DEBUG

uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200
  id: uart_bus
  
custom_component:
- id: air_purifier
  lambda: |-
    auto air_purifier = new XiaomiAirPurifier(id(uart_bus));
    App.register_component(air_purifier);
    return {air_purifier};
  
  components:
    id: ap_custom

text_sensor:
- platform: custom
  id: model
  lambda: |-
    auto cc = static_cast<XiaomiAirPurifier*>(id(ap_custom));
    return {
      cc->model_name,
      cc->mcu_firmware
    };

  text_sensors:
  - name: model
  - name: mcu

sensor:
- platform: custom
  lambda: |-
    auto cc = static_cast<XiaomiAirPurifier*>(id(ap_custom));
    return {
      cc->aqi_sensor,
      cc->temperature_sensor,
      cc->humidity_sensor
    };
  
  sensors:
  - name: AQI
  - name: Temperature
  - name: Humidity

switch:
- platform: custom
  lambda: |-
    auto cc = static_cast<XiaomiAirPurifier*>(id(ap_custom));
    return {cc};

  switches:
  - name: Power