name: Build

on: [push, pull_request]

jobs:
  build_esp32_fw:
    # Don't use the esphome-lint docker image because it may contain outdated requirements.
    # This way, all dependencies are cached via the cache action.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Update pip and deps
        run: |
          python -m pip install --upgrade pip
          pip install esphome
      - name: Build ESPHome firmware
        run: |
          mkdir $GITHUB_WORKSPACE/.out
          cd esp32/esphome
          cp secrets.yaml.dist secrets.yaml
          esphome module.yaml compile
          ls -lh .build/.pioenvs/xiaomi_air_purifier/firmware.bin
          cp .build/.pioenvs/xiaomi_air_purifier/firmware.bin $GITHUB_WORKSPACE/.out/firmware.bin
          ls -lh $GITHUB_WORKSPACE/.out/firmware.bin
      - name: Upload firmware as build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ESPHome_Firmware
          path: ${{ github.workspace }}/.out/firmware.bin